const GB_TO_BYTES = 1024 * 1024 * 1024;

const limits = {
  free: {
    projects: 1,
    teamMembers: 1,
    storageGB: 0.1,
    features: ["1 Active Project", "100MB Storage", "Community Support"],
  },
  pro: {
    projects: 5,
    teamMembers: 3,
    storageGB: 10,
    features: [
      "5 Active Projects",
      "10GB Storage",
      "Priority Support",
      "Remove Branding",
    ],
  },
  agency: {
    projects: -1,
    teamMembers: 10,
    storageGB: 100,
    features: [
      "Unlimited Projects",
      "100GB Storage",
      "Dedicated Account Manager",
      "White Labeling",
    ],
  },
};

export const planDefinitions = [
  {
    name: "Free Trial",
    planType: "monthly" as const,
    lookupKey: "free_trial",
    stripePriceId: null,
    stripeLTDPriceId: null,
    targetPrice: 0,
    initialPrice: 0,
    currency: "usd",
    isActive: true,
    monthlyCreditsLimit: 50,
    projectsLimit: limits.free.projects,
    teamMembersLimit: limits.free.teamMembers,
    storageLimitBytes: limits.free.storageGB * GB_TO_BYTES,
    features: limits.free.features,
    isFeatured: false,
    order: 0,
  },
  {
    name: "Pro Monthly",
    planType: "monthly" as const,
    lookupKey: "pro_monthly",
    stripePriceId: null,
    stripeLTDPriceId: null,
    targetPrice: 29,
    initialPrice: 49,
    currency: "usd",
    isActive: true,
    monthlyCreditsLimit: 1000,
    projectsLimit: limits.pro.projects,
    teamMembersLimit: limits.pro.teamMembers,
    storageLimitBytes: limits.pro.storageGB * GB_TO_BYTES,
    features: limits.pro.features,
    isFeatured: true,
    order: 1,
  },
  {
    name: "Pro Yearly",
    planType: "monthly" as const,
    lookupKey: "pro_yearly",
    stripePriceId: null,
    stripeLTDPriceId: null,
    targetPrice: 290,
    initialPrice: 490,
    currency: "usd",
    isActive: true,
    monthlyCreditsLimit: 1000,
    projectsLimit: limits.pro.projects,
    teamMembersLimit: limits.pro.teamMembers,
    storageLimitBytes: limits.pro.storageGB * GB_TO_BYTES,
    features: limits.pro.features,
    isFeatured: false,
    order: 2,
  },
  {
    name: "Agency Lifetime",
    planType: "ltd" as const,
    lookupKey: "agency_ltd",
    stripePriceId: null,
    stripeLTDPriceId: null,
    ltdPrice: 499,
    initialPrice: 999,
    currency: "usd",
    isActive: true,
    monthlyCreditsLimit: 5000,
    projectsLimit: limits.agency.projects,
    teamMembersLimit: limits.agency.teamMembers,
    storageLimitBytes: limits.agency.storageGB * GB_TO_BYTES,
    features: limits.agency.features,
    isFeatured: false,
    order: 3,
    ltdCampaignIdentifier: "EARLY_ADOPTER_2025",
    stackLevel: 3,
    ltdPurchaseCodeRequired: true,
  },
];

export type PlanDefinition = (typeof planDefinitions)[0];
